In [2]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

# Load datasets
providers = pd.read_csv("../data/raw_data/providers_data.csv")
receivers = pd.read_csv("../data/raw_data/receivers_data.csv")
food_listings = pd.read_csv("../data/raw_data/food_listings_data.csv")
claims = pd.read_csv("../data/raw_data/claims_data.csv")

In [3]:
def basic_eda(df, name):
    print("=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    print(df.head())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nUnique Values:")
    print(df.nunique())

    print("\nSummary Statistics:")
    print(df.describe(include="all"))

In [4]:
basic_eda(providers, "Providers")
basic_eda(receivers, "Receivers")
basic_eda(food_listings, "Food Listings")
basic_eda(claims, "Claims")

================================================================================
DATASET: Providers
================================================================================

Shape:
(1000, 6)

Columns:
['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact']

Data Types:
Provider_ID     int64
Name           object
Type           object
Address        object
City           object
Contact        object
dtype: object

First 5 Rows:
   Provider_ID                         Name           Type  \
0            1             Gonzales-Cochran    Supermarket
1            2  Nielsen, Johnson and Fuller  Grocery Store
2            3                 Miller-Black    Supermarket
3            4   Clark, Prince and Williams  Grocery Store
4            5               Coleman-Farley  Grocery Store

                                                 Address            City  \
0    74347 Christopher Extensions\nAndreamouth, OK 91839     New Jessica
1               91228 Hanson Stream\nWelchtown, OR 27136     East Sheena
2  561 Martinez Point Suite 507\nGuzmanchester, WA 94320  Lake Jesusview
3         467 Bell Trail Suite 409\nPort Jesus, IA 61188     Mendezmouth
4      078 Matthew Creek Apt. 319\nSaraborough, MA 53978   Valentineside

                Contact
0       +1-600-220-0480
1  +1-925-283-8901x6297
2      001-517-295-2206
3      556.944.8935x401
4          193.714.6577

Missing Values:
Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

Duplicate Rows:
0

Unique Values:
Provider_ID    1000
Name            973
Type              4
Address        1000
City            963
Contact        1000
dtype: int64

Summary Statistics:
        Provider_ID            Name         Type  \
count   1000.000000            1000         1000
unique          NaN             973            4
top             NaN  Brown and Sons  Supermarket
freq            NaN               4          262
mean     500.500000             NaN          NaN
std      288.819436             NaN          NaN
min        1.000000             NaN          NaN
25%      250.750000             NaN          NaN
50%      500.500000             NaN          NaN
75%      750.250000             NaN          NaN
max     1000.000000             NaN          NaN

                                                    Address  \
count                                                  1000
unique                                                 1000
top     74347 Christopher Extensions\nAndreamouth, OK 91839
freq                                                      1
mean                                                    NaN
std                                                     NaN
min                                                     NaN
25%                                                     NaN
50%                                                     NaN
75%                                                     NaN
max                                                     NaN

                            City          Contact
count                       1000             1000
unique                       963             1000
top     South Christopherborough  +1-600-220-0480
freq                           3                1
mean                         NaN              NaN
std                          NaN              NaN
min                          NaN              NaN
25%                          NaN              NaN
50%                          NaN              NaN
75%                          NaN              NaN
max                          NaN              NaN
================================================================================
DATASET: Receivers
================================================================================

Shape:
(1000, 5)

Columns:
['Receiver_ID', 'Name', 'Type', 'City', 'Contact']

Data Types:
Receiver_ID     int64
Name           object
Type           object
City           object
Contact        object
dtype: object

First 5 Rows:
   Receiver_ID          Name        Type               City           Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     (955)922-5295
1            2  Laurie Ramos  Individual         Lewisburgh      761.042.1570
2            3  Ashley Mckee         NGO  South Randalltown  691-023-0094x856
3            4    Erika Rose         NGO   South Shaneville        8296491111
4            5   John Romero  Individual          Bakerport      067.491.0154

Missing Values:
Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

Duplicate Rows:
0

Unique Values:
Receiver_ID    1000
Name            992
Type              4
City            966
Contact        1000
dtype: int64

Summary Statistics:
        Receiver_ID           Name  Type             City        Contact
count   1000.000000           1000  1000             1000           1000
unique          NaN            992     4              966           1000
top             NaN  Heather Brown   NGO  New Christopher  (955)922-5295
freq            NaN              2   274                3              1
mean     500.500000            NaN   NaN              NaN            NaN
std      288.819436            NaN   NaN              NaN            NaN
min        1.000000            NaN   NaN              NaN            NaN
25%      250.750000            NaN   NaN              NaN            NaN
50%      500.500000            NaN   NaN              NaN            NaN
75%      750.250000            NaN   NaN              NaN            NaN
max     1000.000000            NaN   NaN              NaN            NaN
================================================================================
DATASET: Food Listings
================================================================================

Shape:
(1000, 9)

Columns:
['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID', 'Provider_Type', 'Location', 'Food_Type', 'Meal_Type']

Data Types:
Food_ID           int64
Food_Name        object
Quantity          int64
Expiry_Date      object
Provider_ID       int64
Provider_Type    object
Location         object
Food_Type        object
Meal_Type        object
dtype: object

First 5 Rows:
   Food_ID Food_Name  Quantity Expiry_Date  Provider_ID     Provider_Type  \
0        1     Bread        43   3/17/2025          110     Grocery Store
1        2      Soup        22   3/24/2025          791     Grocery Store
2        3    Fruits        46   3/28/2025          478  Catering Service
3        4    Fruits        15   3/16/2025          930        Restaurant
4        5      Soup        14   3/19/2025          279        Restaurant

           Location       Food_Type  Meal_Type
0  South Kellyville  Non-Vegetarian  Breakfast
1        West James  Non-Vegetarian     Dinner
2       Lake Regina           Vegan  Breakfast
3         Kellytown           Vegan      Lunch
4        Garciaport           Vegan     Dinner

Missing Values:
Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

Duplicate Rows:
0

Unique Values:
Food_ID          1000
Food_Name          10
Quantity           50
Expiry_Date        15
Provider_ID       637
Provider_Type       4
Location          624
Food_Type           3
Meal_Type           4
dtype: int64

Summary Statistics:
            Food_ID Food_Name     Quantity Expiry_Date  Provider_ID  \
count   1000.000000      1000  1000.000000        1000     1000.000
unique          NaN        10          NaN          15          NaN
top             NaN      Rice          NaN   3/24/2025          NaN
freq            NaN       114          NaN          76          NaN
mean     500.500000       NaN    25.794000         NaN      497.497
std      288.819436       NaN    14.609894         NaN      291.681
min        1.000000       NaN     1.000000         NaN        1.000
25%      250.750000       NaN    13.000000         NaN      241.000
50%      500.500000       NaN    26.000000         NaN      498.500
75%      750.250000       NaN    39.000000         NaN      752.000
max     1000.000000       NaN    50.000000         NaN     1000.000

       Provider_Type   Location   Food_Type  Meal_Type
count           1000       1000        1000       1000
unique             4        624           3          4
top      Supermarket  New Carol  Vegetarian  Breakfast
freq             267          6         336        254
mean             NaN        NaN         NaN        NaN
std              NaN        NaN         NaN        NaN
min              NaN        NaN         NaN        NaN
25%              NaN        NaN         NaN        NaN
50%              NaN        NaN         NaN        NaN
75%              NaN        NaN         NaN        NaN
max              NaN        NaN         NaN        NaN
================================================================================
DATASET: Claims
================================================================================

Shape:
(1000, 5)

Columns:
['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp']

Data Types:
Claim_ID        int64
Food_ID         int64
Receiver_ID     int64
Status         object
Timestamp      object
dtype: object

First 5 Rows:
   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

Missing Values:
Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

Duplicate Rows:
0

Unique Values:
Claim_ID       1000
Food_ID         647
Receiver_ID     624
Status            3
Timestamp       976
dtype: int64

Summary Statistics:
           Claim_ID      Food_ID  Receiver_ID     Status      Timestamp
count   1000.000000  1000.000000  1000.000000       1000           1000
unique          NaN          NaN          NaN          3            976
top             NaN          NaN          NaN  Completed  3/5/2025 1:43
freq            NaN          NaN          NaN        339              3
mean     500.500000   502.163000   492.437000        NaN            NaN
std      288.819436   292.462255   284.487869        NaN            NaN
min        1.000000     1.000000     1.000000        NaN            NaN
25%      250.750000   233.750000   256.000000        NaN            NaN
50%      500.500000   504.500000   480.500000        NaN            NaN
75%      750.250000   762.000000   742.250000        NaN            NaN
max     1000.000000   999.000000  1000.000000        NaN            NaN

In [5]:
for col in providers.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(providers[col].value_counts(dropna=False).head(10))

Name
Name
Brown and Sons       4
Williams PLC         3
Smith Inc            3
Miller Ltd           3
Miller Inc           3
Robinson and Sons    2
Davis Ltd            2
Brown Ltd            2
Jackson LLC          2
Alexander PLC        2
Name: count, dtype: int64

Type
Type
Supermarket         262
Grocery Store       256
Restaurant          246
Catering Service    236
Name: count, dtype: int64

Address
Address
74347 Christopher Extensions\nAndreamouth, OK 91839        1
91228 Hanson Stream\nWelchtown, OR 27136                   1
561 Martinez Point Suite 507\nGuzmanchester, WA 94320      1
467 Bell Trail Suite 409\nPort Jesus, IA 61188             1
078 Matthew Creek Apt. 319\nSaraborough, MA 53978          1
1889 Barnes Gateway\nAdamview, ID 87971                    1
1842 Villarreal Shores\nWilliamfort, CT 44529              1
4770 Miller Light Suite 260\nNew Charlesville, AR 97075    1
169 Scott Keys Suite 000\nEast Michelle, HI 57025          1
71458 Mark Field Apt. 252\nNorth Alexland, TX 02693        1
Name: count, dtype: int64

City
City
South Christopherborough    3
New Carol                   3
Lake Benjamin               2
South Thomas                2
Bradleyport                 2
New Lisa                    2
North Michelle              2
North Kevinhaven            2
West Lauraborough           2
New John                    2
Name: count, dtype: int64

Contact
Contact
+1-600-220-0480         1
+1-925-283-8901x6297    1
001-517-295-2206        1
556.944.8935x401        1
193.714.6577            1
144-860-6074x60544      1
(563)889-7190           1
+1-521-027-8120x3301    1
898-609-2609x844        1
(740)949-2480x40566     1
Name: count, dtype: int64

In [6]:
# Convert string dates to datetime

food_listings["Expiry_Date"] = pd.to_datetime(
    food_listings["Expiry_Date"],
    errors="coerce"
)

claims["Timestamp"] = pd.to_datetime(
    claims["Timestamp"],
    errors="coerce"
)

print(food_listings["Expiry_Date"].dtype)
print(claims["Timestamp"].dtype)

datetime64[ns]
datetime64[ns]

In [7]:
# Provider IDs in food listings
missing_providers = (
    ~food_listings["Provider_ID"].isin(providers["Provider_ID"])
).sum()

# Food IDs in claims
missing_food = (
    ~claims["Food_ID"].isin(food_listings["Food_ID"])
).sum()

# Receiver IDs in claims
missing_receivers = (
    ~claims["Receiver_ID"].isin(receivers["Receiver_ID"])
).sum()

print("Missing Provider IDs:", missing_providers)
print("Missing Food IDs:", missing_food)
print("Missing Receiver IDs:", missing_receivers)

Missing Provider IDs: 0
Missing Food IDs: 0
Missing Receiver IDs: 0

In [8]:
# Food listing features
food_listings["Expiry_Year"] = food_listings["Expiry_Date"].dt.year
food_listings["Expiry_Month"] = food_listings["Expiry_Date"].dt.month_name()
food_listings["Expiry_Day"] = food_listings["Expiry_Date"].dt.day

# Claim features
claims["Claim_Date"] = claims["Timestamp"].dt.date
claims["Claim_Year"] = claims["Timestamp"].dt.year
claims["Claim_Month"] = claims["Timestamp"].dt.month_name()
claims["Claim_Day"] = claims["Timestamp"].dt.day_name()
claims["Claim_Hour"] = claims["Timestamp"].dt.hour

In [9]:
print(food_listings.head())
print()
print(claims.head())

   Food_ID Food_Name  Quantity Expiry_Date  Provider_ID     Provider_Type  \
0        1     Bread        43  2025-03-17          110     Grocery Store
1        2      Soup        22  2025-03-24          791     Grocery Store
2        3    Fruits        46  2025-03-28          478  Catering Service
3        4    Fruits        15  2025-03-16          930        Restaurant
4        5      Soup        14  2025-03-19          279        Restaurant

           Location       Food_Type  Meal_Type  Expiry_Year Expiry_Month  \
0  South Kellyville  Non-Vegetarian  Breakfast         2025        March
1        West James  Non-Vegetarian     Dinner         2025        March
2       Lake Regina           Vegan  Breakfast         2025        March
3         Kellytown           Vegan      Lunch         2025        March
4        Garciaport           Vegan     Dinner         2025        March

   Expiry_Day
0          17
1          24
2          28
3          16
4          19

   Claim_ID  Food_ID  Receiver_ID     Status           Timestamp  Claim_Date  \
0         1      164          908    Pending 2025-03-05 05:26:00  2025-03-05
1         2      353          391  Cancelled 2025-03-11 10:24:00  2025-03-11
2         3      626          492  Completed 2025-03-21 00:59:00  2025-03-21
3         4       61          933  Cancelled 2025-03-04 09:08:00  2025-03-04
4         5      345          229    Pending 2025-03-14 15:17:00  2025-03-14

   Claim_Year Claim_Month  Claim_Day  Claim_Hour
0        2025       March  Wednesday           5
1        2025       March    Tuesday          10
2        2025       March     Friday           0
3        2025       March    Tuesday           9
4        2025       March     Friday          15

In [10]:
print(food_listings.dtypes)
print()
print(claims.dtypes)

Food_ID                   int64
Food_Name                object
Quantity                  int64
Expiry_Date      datetime64[ns]
Provider_ID               int64
Provider_Type            object
Location                 object
Food_Type                object
Meal_Type                object
Expiry_Year               int32
Expiry_Month             object
Expiry_Day                int32
dtype: object

Claim_ID                int64
Food_ID                 int64
Receiver_ID             int64
Status                 object
Timestamp      datetime64[ns]
Claim_Date             object
Claim_Year              int32
Claim_Month            object
Claim_Day              object
Claim_Hour              int32
dtype: object

In [11]:
food_master = food_listings.merge(
    providers,
    on="Provider_ID",
    how="left",
    suffixes=("", "_provider")
)

food_master.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type,Expiry_Year,Expiry_Month,Expiry_Day,Name,Type,Address,City,Contact
0,1,Bread,43,2025-03-17,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast,2025,March,17,Figueroa-Soto,Grocery Store,"113 Donna Pass\nPort Michaelchester, NE 39187",South Kellyville,(599)442-0494
1,2,Soup,22,2025-03-24,791,Grocery Store,West James,Non-Vegetarian,Dinner,2025,March,24,Aguilar Group,Grocery Store,"292 Torres Village\nJohnland, IL 09607",West James,(390)257-0518x4479
2,3,Fruits,46,2025-03-28,478,Catering Service,Lake Regina,Vegan,Breakfast,2025,March,28,"Lopez, Roach and Roach",Catering Service,"8319 Brandi Place Suite 155\nJamesbury, NC 87170",Lake Regina,001-785-448-3246x762
3,4,Fruits,15,2025-03-16,930,Restaurant,Kellytown,Vegan,Lunch,2025,March,16,Cannon-Garcia,Restaurant,"18680 Krystal Inlet Apt. 200\nEast Janettown, MO 64497",Kellytown,9421508200
4,5,Soup,14,2025-03-19,279,Restaurant,Garciaport,Vegan,Dinner,2025,March,19,"Greene, Wood and Hernandez",Restaurant,"69618 Jacob Stravenue\nSouth Jacobton, OH 42099",Garciaport,238.551.4657

In [12]:
claims_master = claims.merge(
    receivers,
    on="Receiver_ID",
    how="left",
    suffixes=("", "_receiver")
)

claims_master.head()

,Claim_ID,Food_ID,Receiver_ID,Status,Timestamp,Claim_Date,Claim_Year,Claim_Month,Claim_Day,Claim_Hour,Name,Type,City,Contact
0,1,164,908,Pending,2025-03-05 05:26:00,2025-03-05,2025,March,Wednesday,5,Abigail Crawford,NGO,Lake Shawn,(010)152-8668
1,2,353,391,Cancelled,2025-03-11 10:24:00,2025-03-11,2025,March,Tuesday,10,Regina Munoz,NGO,Lake Clinton,585.955.3149
2,3,626,492,Completed,2025-03-21 00:59:00,2025-03-21,2025,March,Friday,0,Julie Lewis,NGO,South Steven,(557)352-3497x4606
3,4,61,933,Cancelled,2025-03-04 09:08:00,2025-03-04,2025,March,Tuesday,9,Jodi Lee,NGO,West Paulfort,3517962649
4,5,345,229,Pending,2025-03-14 15:17:00,2025-03-14,2025,March,Friday,15,Tina Watkins,Shelter,Bushview,7774795306

In [13]:
dashboard_data = claims_master.merge(
    food_master,
    on="Food_ID",
    how="left"
)

dashboard_data.head()

,Claim_ID,Food_ID,Receiver_ID,Status,Timestamp,Claim_Date,Claim_Year,Claim_Month,Claim_Day,Claim_Hour,Name_x,Type_x,City_x,Contact_x,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type,Expiry_Year,Expiry_Month,Expiry_Day,Name_y,Type_y,Address,City_y,Contact_y
0,1,164,908,Pending,2025-03-05 05:26:00,2025-03-05,2025,March,Wednesday,5,Abigail Crawford,NGO,Lake Shawn,(010)152-8668,Dairy,22,2025-03-27,432,Restaurant,Carolchester,Vegan,Dinner,2025,March,27,Meyer and Sons,Restaurant,"08209 Eaton Streets Apt. 968\nSouth Laurenside, RI 88383",Carolchester,001-738-662-6338
1,2,353,391,Cancelled,2025-03-11 10:24:00,2025-03-11,2025,March,Tuesday,10,Regina Munoz,NGO,Lake Clinton,585.955.3149,Fruits,5,2025-03-29,418,Restaurant,Deborahfurt,Non-Vegetarian,Lunch,2025,March,29,"Schwartz, Odonnell and Padilla",Restaurant,"23011 Barnett Falls Apt. 524\nWest Cameron, WY 52614",Deborahfurt,955-658-8107x92494
2,3,626,492,Completed,2025-03-21 00:59:00,2025-03-21,2025,March,Friday,0,Julie Lewis,NGO,South Steven,(557)352-3497x4606,Salad,37,2025-03-29,274,Supermarket,New Dawnborough,Non-Vegetarian,Breakfast,2025,March,29,Shields-Moore,Supermarket,"922 Bailey Overpass Suite 885\nNew William, VA 50509",New Dawnborough,9332911651
3,4,61,933,Cancelled,2025-03-04 09:08:00,2025-03-04,2025,March,Tuesday,9,Jodi Lee,NGO,West Paulfort,3517962649,Fruits,33,2025-03-22,243,Catering Service,West Catherine,Vegetarian,Lunch,2025,March,22,Davis-Hurley,Catering Service,"687 Sparks Forks\nEast Patricia, NC 25546",West Catherine,(172)389-0239x87614
4,5,345,229,Pending,2025-03-14 15:17:00,2025-03-14,2025,March,Friday,15,Tina Watkins,Shelter,Bushview,7774795306,Pasta,14,2025-03-20,346,Grocery Store,Thomasville,Vegan,Lunch,2025,March,20,"Phillips, Wolfe and Martin",Grocery Store,Unit 1376 Box 6294\nDPO AE 62072,Thomasville,001-548-413-4962

In [14]:
food_master.to_csv(
    "../data/processed_data/food_master.csv",
    index=False
)

claims_master.to_csv(
    "../data/processed_data/claims_master.csv",
    index=False
)

dashboard_data.to_csv(
    "../data/processed_data/dashboard_data.csv",
    index=False
)

In [15]:
print(dashboard_data.shape)
print(dashboard_data.columns.tolist())
print(dashboard_data.head())
print(dashboard_data.isnull().sum())

(1000, 30)
['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp', 'Claim_Date', 'Claim_Year', 'Claim_Month', 'Claim_Day', 'Claim_Hour', 'Name_x', 'Type_x', 'City_x', 'Contact_x', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID', 'Provider_Type', 'Location', 'Food_Type', 'Meal_Type', 'Expiry_Year', 'Expiry_Month', 'Expiry_Day', 'Name_y', 'Type_y', 'Address', 'City_y', 'Contact_y']
   Claim_ID  Food_ID  Receiver_ID     Status           Timestamp  Claim_Date  \
0         1      164          908    Pending 2025-03-05 05:26:00  2025-03-05
1         2      353          391  Cancelled 2025-03-11 10:24:00  2025-03-11
2         3      626          492  Completed 2025-03-21 00:59:00  2025-03-21
3         4       61          933  Cancelled 2025-03-04 09:08:00  2025-03-04
4         5      345          229    Pending 2025-03-14 15:17:00  2025-03-14

   Claim_Year Claim_Month  Claim_Day  Claim_Hour            Name_x   Type_x  \
0        2025       March  Wednesday           5  Abigail Crawford      NGO
1        2025       March    Tuesday          10      Regina Munoz      NGO
2        2025       March     Friday           0       Julie Lewis      NGO
3        2025       March    Tuesday           9          Jodi Lee      NGO
4        2025       March     Friday          15      Tina Watkins  Shelter

          City_x           Contact_x Food_Name  Quantity Expiry_Date  \
0     Lake Shawn       (010)152-8668     Dairy        22  2025-03-27
1   Lake Clinton        585.955.3149    Fruits         5  2025-03-29
2   South Steven  (557)352-3497x4606     Salad        37  2025-03-29
3  West Paulfort          3517962649    Fruits        33  2025-03-22
4       Bushview          7774795306     Pasta        14  2025-03-20

   Provider_ID     Provider_Type         Location       Food_Type  Meal_Type  \
0          432        Restaurant     Carolchester           Vegan     Dinner
1          418        Restaurant      Deborahfurt  Non-Vegetarian      Lunch
2          274       Supermarket  New Dawnborough  Non-Vegetarian  Breakfast
3          243  Catering Service   West Catherine      Vegetarian      Lunch
4          346     Grocery Store      Thomasville           Vegan      Lunch

   Expiry_Year Expiry_Month  Expiry_Day                          Name_y  \
0         2025        March          27                  Meyer and Sons
1         2025        March          29  Schwartz, Odonnell and Padilla
2         2025        March          29                   Shields-Moore
3         2025        March          22                    Davis-Hurley
4         2025        March          20      Phillips, Wolfe and Martin

             Type_y                                                   Address  \
0        Restaurant  08209 Eaton Streets Apt. 968\nSouth Laurenside, RI 88383
1        Restaurant      23011 Barnett Falls Apt. 524\nWest Cameron, WY 52614
2       Supermarket      922 Bailey Overpass Suite 885\nNew William, VA 50509
3  Catering Service                 687 Sparks Forks\nEast Patricia, NC 25546
4     Grocery Store                          Unit 1376 Box 6294\nDPO AE 62072

            City_y            Contact_y
0     Carolchester     001-738-662-6338
1      Deborahfurt   955-658-8107x92494
2  New Dawnborough           9332911651
3   West Catherine  (172)389-0239x87614
4      Thomasville     001-548-413-4962
Claim_ID         0
Food_ID          0
Receiver_ID      0
Status           0
Timestamp        0
Claim_Date       0
Claim_Year       0
Claim_Month      0
Claim_Day        0
Claim_Hour       0
Name_x           0
Type_x           0
City_x           0
Contact_x        0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
Expiry_Year      0
Expiry_Month     0
Expiry_Day       0
Name_y           0
Type_y           0
Address          0
City_y           0
Contact_y        0
dtype: int64

In [16]:
dashboard_data = dashboard_data.rename(columns={
    "Name_x": "Receiver_Name",
    "Type_x": "Receiver_Type",
    "City_x": "Receiver_City",
    "Contact_x": "Receiver_Contact",
    "Name_y": "Provider_Name",
    "Type_y": "Provider_Category",
    "City_y": "Provider_City",
    "Contact_y": "Provider_Contact"
})

dashboard_data.head()

,Claim_ID,Food_ID,Receiver_ID,Status,Timestamp,Claim_Date,Claim_Year,Claim_Month,Claim_Day,Claim_Hour,Receiver_Name,Receiver_Type,Receiver_City,Receiver_Contact,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type,Expiry_Year,Expiry_Month,Expiry_Day,Provider_Name,Provider_Category,Address,Provider_City,Provider_Contact
0,1,164,908,Pending,2025-03-05 05:26:00,2025-03-05,2025,March,Wednesday,5,Abigail Crawford,NGO,Lake Shawn,(010)152-8668,Dairy,22,2025-03-27,432,Restaurant,Carolchester,Vegan,Dinner,2025,March,27,Meyer and Sons,Restaurant,"08209 Eaton Streets Apt. 968\nSouth Laurenside, RI 88383",Carolchester,001-738-662-6338
1,2,353,391,Cancelled,2025-03-11 10:24:00,2025-03-11,2025,March,Tuesday,10,Regina Munoz,NGO,Lake Clinton,585.955.3149,Fruits,5,2025-03-29,418,Restaurant,Deborahfurt,Non-Vegetarian,Lunch,2025,March,29,"Schwartz, Odonnell and Padilla",Restaurant,"23011 Barnett Falls Apt. 524\nWest Cameron, WY 52614",Deborahfurt,955-658-8107x92494
2,3,626,492,Completed,2025-03-21 00:59:00,2025-03-21,2025,March,Friday,0,Julie Lewis,NGO,South Steven,(557)352-3497x4606,Salad,37,2025-03-29,274,Supermarket,New Dawnborough,Non-Vegetarian,Breakfast,2025,March,29,Shields-Moore,Supermarket,"922 Bailey Overpass Suite 885\nNew William, VA 50509",New Dawnborough,9332911651
3,4,61,933,Cancelled,2025-03-04 09:08:00,2025-03-04,2025,March,Tuesday,9,Jodi Lee,NGO,West Paulfort,3517962649,Fruits,33,2025-03-22,243,Catering Service,West Catherine,Vegetarian,Lunch,2025,March,22,Davis-Hurley,Catering Service,"687 Sparks Forks\nEast Patricia, NC 25546",West Catherine,(172)389-0239x87614
4,5,345,229,Pending,2025-03-14 15:17:00,2025-03-14,2025,March,Friday,15,Tina Watkins,Shelter,Bushview,7774795306,Pasta,14,2025-03-20,346,Grocery Store,Thomasville,Vegan,Lunch,2025,March,20,"Phillips, Wolfe and Martin",Grocery Store,Unit 1376 Box 6294\nDPO AE 62072,Thomasville,001-548-413-4962

In [17]:
dashboard_data.to_csv(
    "../data/processed_data/dashboard_data.csv",
    index=False
)